const crypto=require('crypto');
const registerRtcRoutes=require('./rtc-routes');
module.exports=function registerCaptionRoutes({app,io,getDb,auth}){
 const db=()=>getDb(),clean=(v,n=500)=>String(v??'').trim().slice(0,n),cache=new Map(),managers=['admin','tech','rector','prorector','dean','tutor'];
 async function lessonAccess(user,lessonId){if(!db())return false;const l=await db().collection('lessons').findOne({id:lessonId},{projection:{teacherUsername:1,group:1}});if(!l)return false;if(managers.includes(user.role))return true;if(user.role==='teacher')return l.teacherUsername===user.sub;if(user.role==='student')return Boolean(user.group)&&l.group===user.group;return false}
 async function subjectAccess(user,subjectId){if(!db())return false;const s=await db().collection('subjects').findOne({id:subjectId},{projection:{teacherUsername:1,groups:1}});if(!s)return false;if(managers.includes(user.role))return true;if(user.role==='teacher')return s.teacherUsername===user.sub;if(user.role==='student')return Boolean(user.group)&&(s.groups||[]).includes(user.group);return false}
 async function roomAllowed(user,roomId){if(roomId==='general')return managers.includes(user.role);if(roomId.startsWith('lesson-'))return lessonAccess(user,clean(roomId.slice(7),80));if(roomId.startsWith('subject-'))return subjectAccess(user,clean(roomId.slice(8),80));if(roomId.startsWith('group-')){const g=clean(roomId.slice(6),60);if(managers.includes(user.role))return true;if(user.role==='student')return Boolean(user.group)&&user.group===g;if(user.role==='teacher'&&db()){const c=await db().collection('lessons').countDocuments({teacherUsername:user.sub,group:g},{limit:1});return c>0}return false}return managers.includes(user.role)}
 async function canPublish(user,lessonId){if(!db())return false;const l=await db().collection('lessons').findOne({id:lessonId},{projection:{teacherUsername:1}});return Boolean(l)&&(l.teacherUsername===user.sub||managers.includes(user.role))}
 async function translate(text,target,source='auto'){if(!text||target===source||cache.get(`${source}|${target}|${text}`))return cache.get(`${source}|${target}|${text}`)||text;const key=`${source}|${target}|${text}`;let out=text;try{const ctrl=new AbortController(),t=setTimeout(()=>ctrl.abort(),3500),url=`https://translate.googleapis.com/translate_a/single?client=gtx&sl=${encodeURIComponent(source||'auto')}&tl=${encodeURIComponent(target)}&dt=t&q=${encodeURIComponent(text)}`;const r=await fetch(url,{signal:ctrl.signal,headers:{'User-Agent':'Mozilla/5.0'}});clearTimeout(t);if(r.ok){const d=await r.json();out=(d?.[0]||[]).map(x=>x?.[0]||'').join('').trim()||text}}catch{}cache.set(key,out);if(cache.size>500)cache.delete(cache.keys().next().value);return out}
 registerRtcRoutes({app,auth,getDb});
 app.get('/api/captions/status',auth,(req,res)=>res.json({ok:true,languages:['uz','ru','en'],speechRecognition:'browser',translation:'cloud',transcript:true}));
 app.get('/api/captions/:lessonId',auth,async(req,res)=>{try{const lessonId=clean(req.params.lessonId,80);if(!(await lessonAccess(req.user,lessonId)))return res.status(403).json({ok:false,error:'lesson_access_denied'});if(!db())return res.json({ok:true,items:[]});const items=await db().collection('caption_lines').find({lessonId},{projection:{_id:0}}).sort({at:1}).limit(5000).toArray();res.set('Cache-Control','no-store');res.json({ok:true,items})}catch(e){res.status(500).json({ok:false,error:'caption_history_failed'})}});
 io.on('connection',socket=>{
  socket.removeAllListeners('edu:room:join');socket.removeAllListeners('edu:chat:send');
  socket.on('edu:room:join',async(roomId,ack)=>{const rid=clean(roomId,100);if(!rid||!(await roomAllowed(socket.user,rid))){socket.emit('edu:room:error',{error:'room_access_denied'});ack?.({ok:false,error:'room_access_denied'});return}if(socket.data.eduRoom)socket.leave(socket.data.eduRoom);const room=`edu:${rid}`;socket.join(room);socket.data.eduRoom=room;socket.data.eduRoomId=rid;const count=io.sockets.adapter.rooms.get(room)?.size||1;io.to(room).emit('edu:presence',{online:count});ack?.({ok:true})});
  socket.on('edu:chat:send',async(payload,ack)=>{const rid=socket.data.eduRoomId,text=clean(payload?.text,1200);if(!rid||!text||!(await roomAllowed(socket.user,rid))){ack?.({ok:false,error:'room_access_denied'});return}const msg={id:`msg_${crypto.randomUUID()}`,roomId:rid,text,username:socket.user.sub,name:socket.user.name,role:socket.user.role,createdAt:new Date().toISOString()};if(db())await db().collection('messages').insertOne(msg);io.to(`edu:${rid}`).emit('edu:chat:message',msg);ack?.({ok:true})});
  socket.on('caption:publish',async(payload,ack)=>{try{const lessonId=clean(payload?.lessonId,80),text=clean(payload?.text,260),source=clean(payload?.sourceLang,5)||'auto';if(!lessonId||!text||!(await canPublish(socket.user,lessonId))){ack?.({ok:false,error:'forbidden'});return}const targets=['uz','ru','en'],translated={};for(const lang of targets)translated[lang]=source.startsWith(lang)?text:await translate(text,lang,source==='auto'?'auto':source.slice(0,2));const line={lessonId,text,sourceLang:source,translations:translated,speaker:socket.user.name,username:socket.user.sub,at:new Date().toISOString()};if(db())await db().collection('caption_lines').insertOne({...line,createdAt:new Date()}).catch(()=>{});io.to(`lesson:${lessonId}`).emit('caption:line',line);ack?.({ok:true})}catch{ack?.({ok:false,error:'caption_failed'})}});
  socket.on('disconnect',()=>{if(!socket.data.eduRoom)return;const count=io.sockets.adapter.rooms.get(socket.data.eduRoom)?.size||0;io.to(socket.data.eduRoom).emit('edu:presence',{online:count})});
 });
};
