services:
  - type: web
    name: qdtu-masofaviy
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_NAME
        value: QDTU Masofaviy Ta'lim
