const crypto=require('crypto');
const multer=require('multer');
const mammoth=require('mammoth');
const sanitizeHtml=require('sanitize-html');
const {GridFSBucket,ObjectId}=require('mongodb');
const {Readable}=require('stream');

module.exports=function registerVideoRoutes({app,getDb,auth,allow}){
 const db=()=>getDb(),clean=(v,n=300)=>String(v??'').trim().slice(0,n),id=p=>`${p}_${crypto.randomUUID()}`,managers=['admin','tech','rector','prorector','dean','tutor'];
 const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:25*1024*1024,files:6}});
 async function ensure(){if(!db())return;await Promise.all([db().collection('video_lessons').createIndex({groups:1,publishedAt:-1}),db().collection('video_lessons').createIndex({teacherUsername:1,publishedAt:-1}),db().collection('video_lessons').createIndex({subjectId:1,publishedAt:-1}),db().collection('video_comments').createIndex({videoId:1,createdAt:1}),db().collection('video_likes').createIndex({videoId:1,username:1},{unique:true})]).catch(()=>{})}
 async function video(idv){return db()?db().collection('video_lessons').findOne({id:clean(idv,80)}):null}
 function canView(user,v){if(!user||!v||v.published===false)return false;if(managers.includes(user.role))return true;if(user.role==='teacher')return v.teacherUsername===user.sub;if(user.role==='student'){const gs=Array.isArray(v.groups)?v.groups:[];return gs.length===0||(Boolean(user.group)&&gs.includes(user.group))}return false}
 function canEdit(user,v){return Boolean(v)&&(managers.includes(user.role)||(user.role==='teacher'&&v.teacherUsername===user.sub))}
 function ytId(url){try{const u=new URL(url);if(u.hostname==='youtu.be')return u.pathname.split('/').filter(Boolean)[0]||'';if(u.hostname.includes('youtube.com')){if(u.pathname==='/watch')return u.searchParams.get('v')||'';const p=u.pathname.split('/').filter(Boolean);if(['shorts','embed','live'].includes(p[0]))return p[1]||''}}catch{}return''}
 function autoThumb(url){const y=ytId(url);return y?`https://i.ytimg.com/vi/${y}/hqdefault.jpg`:''}
 function detectProvider(url,requested){if(requested)return clean(requested,30);if(ytId(url))return'youtube';if(/\.(mp4|webm|m3u8)(\?|$)/i.test(url))return'video';return'link'}
 function score(v,p){let s=Number(v.featured?1:0);if(p?.group&&(v.groups||[]).includes(p.group))s+=8;if(p?.course&&String(v.course||'')===String(p.course))s+=3;if(p?.direction&&v.direction&&String(v.direction).toLowerCase()===String(p.direction).toLowerCase())s+=3;return s}
 function bucket(){return new GridFSBucket(db(),{bucketName:'learning_files'})}
 async function saveBuffer(buf,filename,contentType,metadata={}){return new Promise((resolve,reject)=>{const s=bucket().openUploadStream(filename,{contentType,metadata});Readable.from(buf).pipe(s).on('error',reject).on('finish',()=>resolve(s.id))})}
 async function readBuffer(fileId){return new Promise((resolve,reject)=>{const chunks=[];bucket().openDownloadStream(new ObjectId(String(fileId))).on('data',c=>chunks.push(c)).on('error',reject).on('end',()=>resolve(Buffer.concat(chunks)))})}
 function safeObjectId(v){try{return new ObjectId(String(v))}catch{return null}}
 app.use('/api/videos',async(req,res,next)=>{try{await ensure();next()}catch(e){next(e)}});
 app.get('/api/videos',auth,async(req,res)=>{if(!db())return res.json({ok:true,items:[]});const q={published:{$ne:false}};if(req.user.role==='student')q.$or=[{groups:req.user.group},{groups:{$size:0}},{groups:{$exists:false}}];else if(req.user.role==='teacher')q.teacherUsername=req.user.sub;if(req.query.subjectId)q.subjectId=clean(req.query.subjectId,80);if(req.query.group&&managers.includes(req.user.role))q.groups=clean(req.query.group,60);let items=await db().collection('video_lessons').find(q,{projection:{_id:0}}).sort({featured:-1,publishedAt:-1,createdAt:-1}).limit(200).toArray();if(req.user.role==='student'){const p=await db().collection('users').findOne({username:req.user.sub},{projection:{group:1,course:1,direction:1}});items=items.map(x=>({...x,recommendationScore:score(x,p)})).sort((a,b)=>(b.recommendationScore||0)-(a.recommendationScore||0)||new Date(b.publishedAt||0)-new Date(a.publishedAt||0))}res.json({ok:true,items})});
 app.get('/api/videos/:id',auth,async(req,res)=>{if(!db())return res.status(503).json({ok:false,error:'db_required'});const v=await video(req.params.id);if(!canView(req.user,v))return res.status(v?403:404).json({ok:false,error:v?'video_access_denied':'not_found'});const liked=Boolean(await db().collection('video_likes').findOne({videoId:v.id,username:req.user.sub},{projection:{_id:1}}));let recommendations=[];const q={published:{$ne:false},id:{$ne:v.id}};if(req.user.role==='student')q.$or=[{groups:req.user.group},{groups:{$size:0}},{groups:{$exists:false}}];else if(req.user.role==='teacher')q.teacherUsername=req.user.sub;const p=req.user.role==='student'?await db().collection('users').findOne({username:req.user.sub},{projection:{group:1,course:1,direction:1}}):null;recommendations=(await db().collection('video_lessons').find(q,{projection:{_id:0}}).sort({publishedAt:-1}).limit(40).toArray()).filter(x=>canView(req.user,x)).map(x=>({...x,recommendationScore:(x.subjectId===v.subjectId?5:0)+score(x,p)})).sort((a,b)=>(b.recommendationScore||0)-(a.recommendationScore||0)).slice(0,8);res.json({ok:true,item:{...v,_id:undefined},liked,recommendations})});
 app.post('/api/videos',auth,allow('teacher','admin','tech','dean'),async(req,res)=>{if(!db())return res.status(503).json({ok:false,error:'db_required'});const groups=Array.isArray(req.body.groups)?req.body.groups.map(x=>clean(x,60)).filter(Boolean):clean(req.body.groups,500).split(',').map(x=>x.trim()).filter(Boolean),subjectId=clean(req.body.subjectId,80);let teacherUsername=req.user.sub,teacher=req.user.name;if(req.user.role==='teacher'){const s=await db().collection('subjects').findOne({id:subjectId},{projection:{teacherUsername:1,groups:1,name:1}});if(!s||s.teacherUsername!==req.user.sub)return res.status(403).json({ok:false,error:'subject_not_assigned'});if(groups.some(g=>!(s.groups||[]).includes(g)))return res.status(403).json({ok:false,error:'group_not_assigned'})}else if(req.body.teacherUsername){const tu=await db().collection('users').findOne({username:clean(req.body.teacherUsername,80).toLowerCase(),role:'teacher',active:{$ne:false}},{projection:{username:1,name:1}});if(!tu)return res.status(400).json({ok:false,error:'teacher_not_found'});teacherUsername=tu.username;teacher=tu.name}const url=clean(req.body.url,1500),manualThumb=clean(req.body.thumbnailUrl,1500);const doc={id:id('vid'),title:clean(req.body.title,180),description:clean(req.body.description,6000),subjectId,subject:clean(req.body.subject,140),groups,course:clean(req.body.course,40),direction:clean(req.body.direction,140),tags:Array.isArray(req.body.tags)?req.body.tags.map(x=>clean(x,40)).filter(Boolean):clean(req.body.tags,500).split(',').map(x=>x.trim()).filter(Boolean),teacherUsername,teacher,url,thumbnailUrl:manualThumb||autoThumb(url),thumbnailMode:manualThumb?'manual-url':autoThumb(url)?'youtube-auto':'fallback',provider:detectProvider(url,req.body.provider),duration:clean(req.body.duration,30),published:req.body.published!==false,featured:Boolean(req.body.featured),attachments:[],views:0,likes:0,createdBy:req.user.sub,createdAt:new Date(),publishedAt:new Date()};if(!doc.title||!doc.url)return res.status(400).json({ok:false,error:'required'});await db().collection('video_lessons').insertOne(doc);res.status(201).json({ok:true,item:{...doc,_id:undefined}})});
 app.patch('/api/videos/:id',auth,allow('teacher','admin','tech','dean'),async(req,res)=>{if(!db())return res.status(503).json({ok:false,error:'db_required'});const v=await video(req.params.id);if(!canEdit(req.user,v))return res.status(v?403:404).json({ok:false,error:v?'forbidden':'not_found'});const patch={updatedAt:new Date()};['title','description','url','thumbnailUrl','provider','duration','course','direction'].forEach(k=>{if(req.body[k]!==undefined)patch[k]=clean(req.body[k],k==='description'?6000:1500)});if(Array.isArray(req.body.groups))patch.groups=req.body.groups.map(x=>clean(x,60)).filter(Boolean);if(Array.isArray(req.body.tags))patch.tags=req.body.tags.map(x=>clean(x,40)).filter(Boolean);if(req.body.url!==undefined&&!req.body.thumbnailUrl){const at=autoThumb(req.body.url);if(at){patch.thumbnailUrl=at;patch.thumbnailMode='youtube-auto'}}if(req.body.published!==undefined)patch.published=Boolean(req.body.published);if(req.body.featured!==undefined)patch.featured=Boolean(req.body.featured);await db().collection('video_lessons').updateOne({id:v.id},{$set:patch});res.json({ok:true})});
 app.post('/api/videos/:id/thumbnail',auth,allow('teacher','admin','tech','dean'),upload.single('thumbnail'),async(req,res)=>{const v=await video(req.params.id);if(!canEdit(req.user,v))return res.status(v?403:404).json({ok:false,error:v?'forbidden':'not_found'});if(!req.file||!/^image\//.test(req.file.mimetype))return res.status(400).json({ok:false,error:'image_required'});const fileId=await saveBuffer(req.file.buffer,`${v.id}-${req.file.originalname}`,req.file.mimetype,{videoId:v.id,kind:'thumbnail'});await db().collection('video_lessons').updateOne({id:v.id},{$set:{thumbnailFileId:String(fileId),thumbnailMode:'uploaded',updatedAt:new Date()}});res.json({ok:true,url:`/api/videos/${encodeURIComponent(v.id)}/thumbnail-file`})});
 app.get('/api/videos/:id/thumbnail-file',auth,async(req,res)=>{const v=await video(req.params.id);if(!canView(req.user,v)||!v.thumbnailFileId)return res.status(404).end();const oid=safeObjectId(v.thumbnailFileId);if(!oid)return res.status(404).end();const f=await db().collection('learning_files.files').findOne({_id:oid});if(!f)return res.status(404).end();res.set('Content-Type',f.contentType||'image/jpeg');res.set('Cache-Control','private, max-age=3600');bucket().openDownloadStream(oid).on('error',()=>res.end()).pipe(res)});
 app.post('/api/videos/:id/attachments',auth,allow('teacher','admin','tech','dean'),upload.array('files',6),async(req,res)=>{const v=await video(req.params.id);if(!canEdit(req.user,v))return res.status(v?403:404).json({ok:false,error:v?'forbidden':'not_found'});const allowed=new Set(['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','text/plain','application/vnd.openxmlformats-officedocument.presentationml.presentation']);const items=[];for(const f of req.files||[]){if(!allowed.has(f.mimetype))continue;const fileId=await saveBuffer(f.buffer,`${v.id}-${f.originalname}`,f.mimetype,{videoId:v.id,kind:'attachment'});items.push({id:id('att'),fileId:String(fileId),name:clean(f.originalname,180),mime:f.mimetype,size:f.size,createdAt:new Date()})}if(items.length)await db().collection('video_lessons').updateOne({id:v.id},{$push:{attachments:{$each:items}},$set:{updatedAt:new Date()}});res.json({ok:true,items})});
 app.get('/api/videos/:id/attachments/:attachmentId/file',auth,async(req,res)=>{const v=await video(req.params.id);if(!canView(req.user,v))return res.status(403).json({ok:false,error:'video_access_denied'});const a=(v.attachments||[]).find(x=>x.id===req.params.attachmentId),oid=a&&safeObjectId(a.fileId);if(!a||!oid)return res.status(404).end();res.set('Content-Type',a.mime||'application/octet-stream');res.set('Content-Disposition',`inline; filename*=UTF-8''${encodeURIComponent(a.name||'file')}`);bucket().openDownloadStream(oid).on('error',()=>res.end()).pipe(res)});
 app.get('/api/videos/:id/attachments/:attachmentId/reader',auth,async(req,res)=>{const v=await video(req.params.id);if(!canView(req.user,v))return res.status(403).json({ok:false,error:'video_access_denied'});const a=(v.attachments||[]).find(x=>x.id===req.params.attachmentId);if(!a)return res.status(404).json({ok:false,error:'not_found'});if(a.mime==='application/pdf')return res.json({ok:true,type:'pdf',url:`/api/videos/${encodeURIComponent(v.id)}/attachments/${encodeURIComponent(a.id)}/file`});if(a.mime==='application/vnd.openxmlformats-officedocument.wordprocessingml.document'){const buf=await readBuffer(a.fileId),out=await mammoth.convertToHtml({buffer:buf});return res.json({ok:true,type:'html',html:sanitizeHtml(out.value,{allowedTags:sanitizeHtml.defaults.allowedTags.concat(['img','h1','h2','h3','table','thead','tbody','tr','th','td']),allowedAttributes:{...sanitizeHtml.defaults.allowedAttributes,img:['src','alt','width','height'],a:['href','name','target']}}),warnings:out.messages?.length||0})}res.json({ok:true,type:'download',url:`/api/videos/${encodeURIComponent(v.id)}/attachments/${encodeURIComponent(a.id)}/file`})});
 app.post('/api/videos/:id/view',auth,async(req,res)=>{if(!db())return res.json({ok:true});const v=await video(req.params.id);if(!canView(req.user,v))return res.status(403).json({ok:false,error:'video_access_denied'});await db().collection('video_lessons').updateOne({id:v.id},{$inc:{views:1}});res.json({ok:true})});
 app.post('/api/videos/:id/like',auth,async(req,res)=>{if(!db())return res.json({ok:true,liked:false});const v=await video(req.params.id);if(!canView(req.user,v))return res.status(403).json({ok:false,error:'video_access_denied'});const videoId=v.id,q={videoId,username:req.user.sub},ex=await db().collection('video_likes').findOne(q);if(ex){await db().collection('video_likes').deleteOne(q);await db().collection('video_lessons').updateOne({id:videoId},{$inc:{likes:-1}});return res.json({ok:true,liked:false})}await db().collection('video_likes').insertOne({...q,createdAt:new Date()});await db().collection('video_lessons').updateOne({id:videoId},{$inc:{likes:1}});res.json({ok:true,liked:true})});
 app.get('/api/videos/:id/comments',auth,async(req,res)=>{if(!db())return res.json({ok:true,items:[]});const v=await video(req.params.id);if(!canView(req.user,v))return res.status(403).json({ok:false,error:'video_access_denied'});const items=await db().collection('video_comments').find({videoId:v.id},{projection:{_id:0}}).sort({createdAt:1}).limit(300).toArray();res.json({ok:true,items})});
 app.post('/api/videos/:id/comments',auth,async(req,res)=>{if(!db())return res.status(503).json({ok:false,error:'db_required'});const v=await video(req.params.id);if(!canView(req.user,v))return res.status(403).json({ok:false,error:'video_access_denied'});const text=clean(req.body.text,1200);if(!text)return res.status(400).json({ok:false,error:'required'});const doc={id:id('vc'),videoId:v.id,username:req.user.sub,name:req.user.name,role:req.user.role,text,parentId:clean(req.body.parentId,80),createdAt:new Date()};await db().collection('video_comments').insertOne(doc);res.status(201).json({ok:true,item:{...doc,_id:undefined}})});
};
