const {spawn}=require('child_process');
const jwt=require('jsonwebtoken');
const {io}=require('socket.io-client');
const path=require('path');
const HTTP_PORT=3910,RTC_PORT=49100,SECRET='qdtuedu-selftest-secret';
const child=spawn(process.execPath,[path.join(__dirname,'server.js')],{env:{...process.env,SFU_HTTP_PORT:String(HTTP_PORT),SFU_RTC_PORT:String(RTC_PORT),SFU_ANNOUNCED_IP:'127.0.0.1',SFU_TOKEN_SECRET:SECRET,SFU_WORKERS:'1',SFU_LOG_LEVEL:'error'},stdio:['ignore','pipe','pipe']});
child.stdout.on('data',d=>process.stdout.write(d));child.stderr.on('data',d=>process.stderr.write(d));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitHealth(){for(let i=0;i<30;i++){try{const r=await fetch(`http://127.0.0.1:${HTTP_PORT}/health`);if(r.ok)return r.json()}catch{}await sleep(500)}throw new Error('health_timeout')}
function emitAck(s,event,payload){return new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error(event+'_timeout')),5000);s.emit(event,payload,r=>{clearTimeout(t);if(!r?.ok)reject(new Error(r?.error||event+'_failed'));else resolve(r)})})}
(async()=>{let socket;try{const h=await waitHealth();if(!h.ok||!h.workers?.length)throw new Error('worker_not_ready');const token=jwt.sign({roomId:'SELFTEST-ROOM',sub:'teacher-test',name:'Teacher Test',role:'teacher',group:'TEST',teacherUsername:'teacher-test'},SECRET,{expiresIn:'5m',issuer:'qdtuedu-web'});socket=io(`http://127.0.0.1:${HTTP_PORT}`,{transports:['websocket'],auth:{token}});await new Promise((resolve,reject)=>{socket.once('connect',resolve);socket.once('connect_error',reject);setTimeout(()=>reject(new Error('socket_timeout')),5000)});const join=await emitAck(socket,'room:join',{roomId:'SELFTEST-ROOM'});if(!join.rtpCapabilities?.codecs?.length)throw new Error('rtp_capabilities_missing');const tr=await emitAck(socket,'transport:create',{direction:'send'});if(!tr.params?.id||!tr.params?.iceParameters||!tr.params?.dtlsParameters)throw new Error('transport_params_missing');console.log('SFU_SELFTEST_PASS',{workers:h.workers.length,rtcPort:h.workers[0].port,transportId:tr.params.id});socket.disconnect();child.kill('SIGTERM');process.exit(0)}catch(e){console.error('SFU_SELFTEST_FAIL',e);try{socket?.disconnect()}catch{}child.kill('SIGTERM');process.exit(1)}})();
